mysql:
 host: "localhost"
 password: "mulesoft2022"
 user: "root"
 dbase: "northwind"
 port: "3306"
 
postgresql:
  url: "jdbc:postgresql://localhost:5432/Northwind"
  password: "mulesoft2022"
  user: "postgres"
  driver_name: "org.postgresql.Driver"
  